### ISSUE TITLE
[기능] Preview에 대한 기능

### ISSUE THREAD

**Issue by kangddong** [doyeonjeong/Tublock#12]
* Preview 버튼 누를 시 푸시 온 것과 같은 애니메이션 View 구현
<img width="277" alt="image" src="https://user-images.githubusercontent.com/50406861/230452857-6c2a89aa-d903-4dd9-a27e-a0ffa5b7e2ae.png">

**Comment by kangddong** [comment]
iPhone SE3 ---------------------------- iPhone 14(노치) ----------------------------- iPhone 14 Pro Max(다이나믹 아일랜드)
<div>
  <img height="500" src="https://user-images.githubusercontent.com/50406861/230947203-81cfa152-dcd3-4f1d-a2cc-d81dec896281.png"/>
  <img height="500" src="https://user-images.githubusercontent.com/50406861/230947328-81675384-59fa-44d9-bacc-5b18b5f89cba.png"/>
  <img height="500" src="https://user-images.githubusercontent.com/50406861/230947368-6dff778f-2cb5-4cf3-b3a1-f0e419c5a2cc.png"/>
</div>

**Comment by kangddong** [comment]
[iPhone Dimension about status bar](https://useyourloaf.com/blog/iphone-14-screen-sizes/)
[iPhone sizes](http://www.idev101.com/code/User_Interface/sizes.html)
[아이폰 부위(?)별 명칭](https://m.blog.naver.com/gundeokji/150159630361)

| 기기명 | status size |
|:---:|:---:|
| iPhone 14 | 47 Points |
| iPhone 14 Pro Max | 59 Points |
| iPhone SE3 | 20 Points |


iPhone 14 47 Points
iPhone 14 Pro Max 59 Points
iPhone SE3 20 Points

**Comment by doyeonjeong** [comment]
혹시 이거 애니메이션 위치 설정할 때 필요한 거라면
View의 상단 부분이 SafeAriaGuide 기준 하한으로 설정하면 동적으로 적용되진 않을까요?

**Comment by kangddong** [comment]
ah ?

**Comment by kangddong** [comment]
완료!
![tublock_notiAnimation](https://user-images.githubusercontent.com/50406861/231224269-c47b1ccc-3e3d-4600-900f-6f0ada5e65ee.gif)
