### ISSUE TITLE
[의견필요] TextView 글자 수에 대한 문의

### ISSUE THREAD

**Issue by kangddong** [doyeonjeong/Tublock#15]
associated #11 

아래 이미지의 텍스트의 길이는 79자에요
![image](https://user-images.githubusercontent.com/50406861/230734110-00aacda6-9589-4f5c-874f-e2627d25a6a0.png)

이 이미지는 50자 이내에서 일반적인 띄어쓰기 포함 문장으로 표현한 것입니다.
![image](https://user-images.githubusercontent.com/50406861/230734208-9d8ca78c-6798-44da-be41-a5cb599c95fb.png)

제 눈에는 충분해 보이는데 50자 충분해보이나요 ?
의견 부탁드려요

**Comment by doyeonjeong** [comment]
음 저는 아래줄도 오른쪽 끝까지 채울 수 있으면 더 좋을 것 같습니다!

언어에 상관없이 2줄 모두 화면 양쪽 가득 채우고 싶은데
언어마다 화면을 차지하는 기본 영역이 다른 점이 신경쓰이네요

[한글 기준]
맨 마지막 문장을 '비비'에서 '비비야 유튜브 그만보자 !!' 까지 완성하면 총 63자인데
널널하게 64자라면 화면을 충분히 채울 수 있을 것 같고,

[영어 소문자 기준]
64자로 제한하면 영문으로 작성할 때는 또 비어보일 것 같네요

메모리에 저장될 수 있는 문자는 78자로 제한(79자 미만)하고,
한글의 경우는 64자까지 입력 가능한 로직을 세우는 건 어떻게 생각해요?

**Comment by kangddong** [comment]
한글 영어구분하는게 너무 빡셀거같은데 ,,,, 아이디어 있어요 ?

**Comment by doyeonjeong** [comment]
그러네요........ 어떻게 구분하지....... 허으으
