### ISSUE TITLE
[버그?] 시뮬레이터에서 설정-스크린타임 접속 불가능..?

### ISSUE THREAD

**Issue by kangddong** [doyeonjeong/Tublock#31]
시뮬레이터에서 스크린타임 API 권한이 오지않아요 .. 

**에러 메세지**
DeviceActivitySample[49671:13252158] [authorization] Failed to fetch authorization status: Optional(Error Domain=FamilyControls.FamilyControlsError Code=3 "(null)")

**status**: notDetermined

**Comment by doyeonjeong** [comment]
엑... 안돼....

**Comment by kangddong** [comment]
https://developer.apple.com/forums/thread/685861
실기기로 테스트 요함

**Comment by doyeonjeong** [comment]
실물 기기 테스트 완료
<div>
<img width="250" src="https://user-images.githubusercontent.com/108422901/234153750-1c8956aa-9cc9-439f-813b-5907ecdc8468.PNG">
<img width="250" src="https://user-images.githubusercontent.com/108422901/234153763-f1b697af-699d-4713-af8f-71d995f5b336.PNG">
<img width="250" src="https://user-images.githubusercontent.com/108422901/234153768-4f65ca65-4743-4533-88e9-b2d1d660bfaa.PNG">
</div>
