### ISSUE TITLE
[Fix] UserDefaults 저장시 Tuple 값 저장 되지 않는 문제

### ISSUE THREAD

**Issue by doyeonjeong** [doyeonjeong/Tublock#42]
<img width="657" alt="스크린샷 2023-04-28 오후 12 50 06" src="https://user-images.githubusercontent.com/108422901/235049954-e9e323b1-553e-467a-88ca-fc199d73f8e3.png">

### 원인

`UserDefaults`는 `Property List` 형식의 데이터만 저장 가능하나,
현재 `BlockTime` 구조체는 `Property List` 형식이 아니기 때문에 오류가 발생했습니다!

### 에러 메시지

```shell
Thread 1: "Attempt to insert non-property list object (hours: 23, minutes: 33) for key maximum Time"
```

### 해결 방안 예시
아직 이렇게 코드를 수정하지는 않았고 #30 UserManager 연동할 때 고도화를 이런식으로 하면 어떨지 의논하고싶어서 올려봐요!

1. BlockTime을 `typealias BlockTime = (hours: Int, minutes: Int)`가 아닌 구조체로 변환:

```swift
struct BlockTime: Equatable {
    let hours: Int
    let minutes: Int
}
```
🧐*구조체로 바꾸는 김에 테스트 코드도 시도해보고싶은데 `Equatable` 프로토콜 추가하는거 어떤가요?

2. BlockTime 구조체를 Dictionary로 변환하는 함수를 작성:

```swift
func blockTimeToDictionary(blockTime: BlockTime) -> [String: Int] {
    return ["hours": blockTime.hours, "minutes": blockTime.minutes]
}

func dictionaryToBlockTime(dictionary: [String: Int]) -> BlockTime {
    return BlockTime(hours: dictionary["hours"] ?? 0, minutes: dictionary["minutes"] ?? 0)
}
```

3. UserDefaultsManager에서 이 함수들을 사용하여 값을 저장하고 읽어오도록 코드 수정:

```swift
struct UserDefaultsManager {
    static let defaults = UserDefaults.standard
    
    static var time: BlockTime {
        get {
            let dictionary = defaults.dictionary(forKey: "maximumTime") as? [String: Int] ?? ["hours": 0, "minutes": 0]
            return dictionaryToBlockTime(dictionary: dictionary)
        }
        set {
            defaults.set(blockTimeToDictionary(blockTime: newValue), forKey: "maximumTime")
        }
    }
}
```

**Comment by doyeonjeong** [comment]
#38

**Comment by kangddong** [comment]
```swift
//    @UserDefaultsWrapper(key: CommonType.MAXIMUM_TIME, defaultValue: (0,0))
    static var time: BlockTime {
        get {
            let ud = UserDefaults.standard
            let baseKey = CommonType.MAXIMUM_TIME
            let hoursKey = baseKey + "_hours"
            let minuteKey = baseKey + "_minute"
            
            guard
                let hours = ud.value(forKey: hoursKey) as? Int,
                let minute = ud.value(forKey: minuteKey) as? Int
            else { return (0, 0)}
            
            return (hours, minute)
        }
        set {
            let ud = UserDefaults.standard
            let baseKey = CommonType.MAXIMUM_TIME
            let hoursKey = baseKey + "_hours"
            let minuteKey = baseKey + "_minute"
            
            ud.setValue(newValue.hours, forKey: hoursKey)
            ud.setValue(newValue.minutes, forKey: minuteKey)
        }
    }
```

**Comment by kangddong** [comment]
BlockTime을 struct 구조체로 변경해도 아마 같은 오류가 알고있어요
커스텀 타입이라서 Encode, Decode 해줘야하는걸로 알아요 ..!

**Comment by doyeonjeong** [comment]
아하 그럼 아래처럼 하면 될까요?!
```swift
struct BlockTime: Equatable, Codable {
    let hours: Int
    let minutes: Int
}
```

**Comment by kangddong** [comment]
문득,,, 이럴거면 BlockTime를 싱글톤으로 디자인하고 init 시점에
Userdefualt에 hours, time을 각각 저장해둔 값으로 이니셜라이저 해두고
didSet 를 활용해서 Userdefualt 저장하는 건 어떨까싶네요 ..~~

```swift
final class BlockTime2 {
    static let shared: BlockTime2 = BlockTime2()
    
    var hours: Int {
        didSet { UserDefaultsManager.hours }
    }
    var minute: Int {
        didSet { UserDefaultsManager.minute }
    }
    
    private init() {
        self.hours = UserDefaultsManager.hours
        self.minute = UserDefaultsManager.minute
    }
}
```

**Comment by kangddong** [comment]
final class BlockTime2 {
    static let shared: BlockTime2 = BlockTime2()
    
    var hours: Int {
        didSet { UserDefaultsManager.hours = hours }
    }
    var minute: Int {
        didSet { UserDefaultsManager.minutes = minute }
    }
    
    private init() {
        self.hours = UserDefaultsManager.hours
        self.minute = UserDefaultsManager.minutes
    }
}

**Comment by doyeonjeong** [comment]
아하 그러게요 어차피 값은 하나일테니까 굳이 Struct로 구현하는 의미가 없겠네요
그래도 BlockTime 이라는 구조체가 있는게 UserDefaults에 직접 변수로 두는 것 보다는 명시적일 것 같아요!

**Comment by kangddong** [comment]
> 아하 그럼 아래처럼 하면 될까요?!
> 
> ```swift
> struct BlockTime: Equatable, Codable {
>     let hours: Int
>     let minutes: Int
> }
> ```

의도가 딕셔너리에 들어갔을 때 중복을 방지하고 싶은거죠 ..? 
저도 그런 실험을 했었는데 중복을 제거하기 위해서는 원본데이터와 비교를 했었어야했어요

**Comment by doyeonjeong** [comment]
> 아하 그러게요 어차피 값은 하나일테니까 굳이 Struct로 구현하는 의미가 없겠네요 그래도 BlockTime 이라는 구조체가 있는게 UserDefaults에 직접 변수로 두는 것 보다는 명시적일 것 같아요!

제가 여기서 구조체라고 표현해서 헷갈렸던거같네요,
BlockTime의 Struct(구조체)를 만들고싶다고 말한게 아니고
UserDefaults에 hours, minutes 이렇게 따로따로 저장하는 것 보다는
Class 형태여도 좋으니까 BlockTime 이라는 타입이 존재했으면 좋겠다! 라고 이해해주면 좋을거같아요.

**Comment by kangddong** [comment]
> 음.. 아뇨 `Equatable`을 사용하면 딕셔너리에 append 하는 시점에 자동으로 중복을 방지할 수 있는건지는 몰랐어요!
> 
> `Equatable`을 쓴 이유는 `BlockTime` 타입이 `UserDefaults`에 제대로 저장되는건지 테스트 코드를 작성하려고 했는데 `Tuple`타입이 `Equatable`하지 않기 때문에 테스트할 수 없다는 오류메세지가 있었고, 실험삼아 `Struct`를 `Equatable` 채택하고 만들어봤는데 테스트코드는 작동할 수 있는 상태였던걸로 기억해요!
> 
> (근데 확실하지 않음... 테스트 코드 작동할 수 있었던게 맞는지 갑자기 가물가물함)

제가 말을 좀 이상하게 했나봐여
> 음.. 아뇨 `Equatable`을 사용하면 딕셔너리에 append 하는 시점에 자동으로 중복을 방지할 수 있는건지는 몰랐어요!
`Equatable`을 사용하면 딕셔너리에 append 하는 시점에 자동으로 중복을 방지 <- 를 제가 고민했던 부분이고

> 중복을 제거하기 위해서는 원본데이터와 비교를 했었어야했어요 **자동으로** `Equatble` 하게 **처리를 못했어요**
위 부분은 실험 실패에 대한 결과였어요

추가적으로 궁금한건 테스트 코드 작성을 VC에서 테스트 목적으로 사용한다는건지, 
Test 타겟에 테스트를 추가하고싶다는건지 이해를 못했어요
 
 이해를 못한 이유는 XCTest 프레임워크를 이용해서 테스트 코드를 작성한다면
 func `test`<function name> {} 같은 형태로 `test` 키워드가 func 의 이름 앞에 명시되어있어야하거든요 
```swift
func blockTimeToDictionary(blockTime: BlockTime) -> [String: Int] {}
func testBlockTimeToDictionary(blockTime: BlockTime) -> [String: Int] {

func dictionaryToBlockTime(dictionary: [String: Int]) -> BlockTime {}
func testDictionaryToBlockTime(dictionary: [String: Int]) -> BlockTime {}
```

**Comment by kangddong** [comment]
만약 `XCTest` 를 import 해서 테스트 코드를 작성하겠다라는 의미가 아니라면
dictionary로 전환하고 저장하는데 있어서 `Tuple`과 `Equtable`이 어떤 관계가 있는걸까요 ?

**Comment by kangddong** [comment]
방금 플레이그라운드에서 아래와 같이 했는데 문제 없었어요 !! Equtable 은 무슨 목적으로 어디에 왜 필요한거에요 ?

```swift
struct BlockTime: Equatable {
    let hours: Int
    let minutes: Int
}

func blockTimeToDictionary(blockTime: BlockTime) -> [String: Int] {
    return ["hours": blockTime.hours, "minutes": blockTime.minutes]
}

func dictionaryToBlockTime(dictionary: [String: Int]) -> BlockTime {
    return BlockTime(hours: dictionary["hours"] ?? 0, minutes: dictionary["minutes"] ?? 0)
}

let blockTime = BlockTime(hours: 3, minutes: 0)
let dict = blockTimeToDictionary(blockTime: blockTime)
print(dict)

let tuple = dictionaryToBlockTime(dictionary: dict)
print(tuple)
```

**Comment by doyeonjeong** [comment]
아하 제가 테스트하려던건 `XCTest` 를 import해서 테스트를 하려던게 맞고
기존 타입인 
`typealias BlockTime = (hours: Int, minutes: Int)`인 상태에서 Test 코드를 아래와 같이 작동했을 때

```swift
func testSaveAndLoadTime() {
        // Test case 1
        let time1 = BlockTime(hours: 1, minutes: 30)
        UserDefaultsManager.time = time1
        XCTAssertEqual(UserDefaultsManager.time, time1)

        // Test case 2
        let time2 = BlockTime(hours: 2, minutes: 45)
        UserDefaultsManager.time = time2
        XCTAssertEqual(UserDefaultsManager.time, time2)
    }
```

<img width="1016" alt="스크린샷 2023-04-28 오후 3 14 11" src="https://user-images.githubusercontent.com/108422901/235068796-2159af16-3b35-475e-a8d7-70b944d1b843.png">

이런 오류가 났었거든요...
그래서 BlockTime이 튜플 타입인 경우, Equatable 프로토콜을 구현할 수 없는 문제라서

```swift
struct BlockTime: Equatable {
    let hours: Int
    let minutes: Int
}
```

그럼 '이런식으로 구조체를 사용하면 되는건가?'라고 생각했던거였어요.
제가 `XCTest`를 자세히는 모른다는 점 참고해주세요...ㅋㅋㅋㅋㅋ



> 만약 `XCTest` 를 import 해서 테스트 코드를 작성하겠다라는 의미가 아니라면 dictionary로 전환하고 저장하는데 있어서 `Tuple`과 `Equtable`이 어떤 관계가 있는걸까요 ?

이부분은 제가 알기로 Dictionary 타입은 값을 변경할 수 있지만,
Tuple은 한번 값이 정해지면 변경할 수 없다는 점 때문에 Tuple 값 형태로는 UserDefaults에 저장할 수 없는게 아닌가?라고 생각하고 있어요..!

**Comment by doyeonjeong** [comment]
말하다보니까 `Equtable` 집착 광공이 된 것 같은데... 그건 아니고...
그냥 테스트 할려고 보니까 저 오류가 떠서 필요한건가 싶었슴다...
미안합니다.......... `XCTest` 사용법 숙지해놓겠습니다............🥲

**Comment by kangddong** [comment]
우리에게 필요한 지식 같아서 공유드려요
[Tuple 은 Hashable 할수없다 ](https://developer.apple.com/forums/thread/109146) 
[향후 Swift가 발전한다면 다음 버전에서는 Tuple 또한 Equatable을 준수할지도 모른다](https://forums.swift.org/t/tuples-conform-to-equatable/32559/4)]

**Comment by kangddong** [comment]
저는 누군가에게 답변을 드리기위해서 의도와 목적을 파악하는게 가장 중요해서 계속 물어봤어요
제가 답변을 할만큼 의도와 목적이 쉽게 파악이 되지않았어요
다음에는 좀 더 잘 파악해볼게요

**Comment by doyeonjeong** [comment]
> 우리에게 필요한 지식 같아서 공유드려요 [Tuple 은 Hashable 할수없다 ](https://developer.apple.com/forums/thread/109146) [향후 Swift가 발전한다면 다음 버전에서는 Tuple 또한 Equatable을 준수할지도 모른다](https://forums.swift.org/t/tuples-conform-to-equatable/32559/4)]

넵 참고해놓을게요 ...!

**Comment by doyeonjeong** [comment]
저도 다음번엔 의도와 목적을 좀 더 명확하게 전달해서 똑같은 질문을 여러번 되풀이 하지 않을 수 있게 질문해볼게요..!

**Comment by kangddong** [comment]
제가 더 많은 지식이 없어서 자꾸 물어봐서 미안해요

**Comment by kangddong** [comment]
저 또한 비비 질문으로 많이 배워요
