### ISSUE TITLE
[Fix] UserDefaultsManager 에 selectedTime 저장하는 로직

### ISSUE THREAD

**Issue by doyeonjeong** [doyeonjeong/Tublock#50]
<img width="934" alt="스크린샷 2023-05-03 오후 4 11 04" src="https://user-images.githubusercontent.com/108422901/235852241-2c98e0c5-1fd8-486a-94ba-23b35a5f3c0a.png">

Tuple값이 아닌 형태로 저장될 수 있도록 수정 필요

**Comment by kangddong** [comment]
네 확인했습니다
