### ISSUE TITLE
[Fix] SetMaximum 기기에서 라벨 안보이는 문제

### ISSUE THREAD

**Issue by doyeonjeong** [doyeonjeong/Tublock#56]
실제 기기에서 `SetMaximumView` - `_timeSettingButton`의 라벨이 보이지않는 문제

**Comment by kangddong** [comment]
어느 레이블이 안 보이는지 스크린샷도 있으면 좋겠어요
기종 명시해주세요 !

**Comment by doyeonjeong** [comment]
![IMG_0851CC239ED4-1](https://user-images.githubusercontent.com/108422901/236686937-d9ebb421-570e-4fc0-8b7e-4a8e5b73eab2.jpeg)
아이폰 SE2 기종에서 안보입니다!

**Comment by kangddong** [comment]
버그 재현했습니다 ~!

![image](https://user-images.githubusercontent.com/50406861/236819100-a77ac946-ac78-453a-82f8-6c3b5053e5dd.png)

![image](https://user-images.githubusercontent.com/50406861/236819222-c136bef5-b25c-40f9-8110-595a3633ef2f.png)

원인은 컬러가 맞았어요.
추가로 다크모드로 인해서 디폴트 컬러 값이 변해서 그래요
아마 지금 비비가 다크모드가 켜져있을 것 같은데 
처리했던 코드 주석한 후에 다크모드 끄고 확인해볼래요 ?

**Comment by doyeonjeong** [comment]
라이트모드로 하니까 라벨 잘 보이네요..!
