### ISSUE TITLE
[UI&UX] Set Maximum UI 개발

### ISSUE THREAD

**Issue by kangddong** [doyeonjeong/Tublock#7]
<img width="331" alt="image" src="https://user-images.githubusercontent.com/50406861/230451044-aadc89eb-6849-417a-8693-de3abde7179d.png">

피그마 영역에 맞춰서 부탁드려요

**Comment by doyeonjeong** [comment]
## 🛠️ 수정 사항
회의하다가 라인을 급하게 그려놓은 걸 깜빡하고 수정 안 했네요
제가 알기론 모바일 그래픽 파일들은 대부분 홀수로 설정되어있는 경우 화면이 깨져 보여서
Figma 파일에 있는 홀수들을 수정할 예정이에요!

예를들어
기존파일 SetMaximum height = `169` -> 수정 후 `170`
<div>
<img width="420" alt="SetMaximum 기존" src="https://user-images.githubusercontent.com/108422901/230520514-66d7e956-5fae-4506-8f75-aed7d131fbfd.png">
<img width="420" alt="SetMaximum 수정" src="https://user-images.githubusercontent.com/108422901/230521750-48a0fb35-35eb-48e6-90b2-af8a309ee7c0.png">
</div>

<br>
오토레이아웃 설정 안되어있는것도 다 걸어놓을게요!<br>
그래야 아래처럼 간격 보기 편할 것 같아서ㅎㅎ 참고해주세요

<img width="529" alt="피그마에서 오토 레이아웃 걸면 보기 쉬운 이유" src="https://media1.giphy.com/media/nSAQMxlAI0WVrVOPDW/giphy.gif">

**Comment by doyeonjeong** [comment]
## 🛠️ 수정 완료
확인했다면 👀 이모티콘 남겨줘요!

<img width="537" alt="스크린샷 2023-04-07 오전 10 33 50" src="https://user-images.githubusercontent.com/108422901/230522502-a8265858-10d6-4725-9e88-03dea804f992.png">

**Comment by kangddong** [comment]
작업 완료되면 Assignees(담당자) 비비가 Close 해줘요 !
지금처럼 수정 사항 생기면 
#7 
#13 
이런식으로 new issue에 기존 이슈와 마일스톤을 엮어주세요 !
마일스톤 close는 서로 이슈에 대해서 확인하고 해요 !
Pull requset 단위는 마일스톤 단위로 하는게 어때요 ?

**Comment by doyeonjeong** [comment]
Assignees(담당자) 가 있었군여? 확인했어요 !
넵 앞으론 수정사항 이슈 번호로 걸어볼게요 !
마일스톤 close는 서로 이슈에 대해서 확인한다는 말은 잘 이해 못 했어요! 한 번 더 설명해 줄 수 있나요?
Pull Requset -> 마일스톤 단위 좋습니당!

**Comment by kangddong** [comment]
아래 사진들이 마일스톤인데요 
마일스톤은 작업에 대한 목표설정 이라고 생각해요
큰 작업(Task)을 마일스톤으로 표현하고
작은 작업(Sub Task)들을 이슈로 관리한다고 생각하면 이해가 편할거같아요

그렇기 때문에 issue들을 close하여 milestone을 close 해야하는 상황일 때 
issue들이 확실히 작업이 됐는지 확인 후에 milestone을 close하자는 의미였어요 !!


<img width="1244" alt="image" src="https://user-images.githubusercontent.com/50406861/230527267-d45d5c8b-b21d-4473-8a08-497cef9bc011.png">

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/50406861/230527313-19434936-bb14-4a04-8163-376007b4e016.png">

**Comment by doyeonjeong** [comment]
오 한번에 이해됐어요!
![감사맨](https://user-images.githubusercontent.com/108422901/230529475-1699fdaf-c216-4c2f-ae61-22e9d7bfe600.gif)
